import type { Listing } from "@/lib/types";

export const demoListings: Listing[] = [
  {
    id: "demo-1",
    title: "Demo: Modern 2-Bedroom Apartment",
    description: "Demonstration inventory only. This record is not a verified property and must be replaced before public launch.",
    property_type: "Apartment",
    location: "Ayeduase",
    city: "Kumasi",
    region: "Ashanti",
    address: "Ayeduase, Kumasi",
    latitude: null,
    longitude: null,
    monthly_rent: 4200,
    bedrooms: 2,
    bathrooms: 2,
    furnishing: "Unfurnished",
    room_type: "2-bedroom apartment",
    occupants: 4,
    lease_term: "12 months",
    amenities: ["Water", "Parking", "Kitchen", "Security"],
    image_urls: [
      "https://images.unsplash.com/photo-1600607687920-4e2a09cf159d?auto=format&fit=crop&w=1200&q=85",
      "https://images.unsplash.com/photo-1600566753086-00f18fb6b3ea?auto=format&fit=crop&w=1200&q=85"
    ],
    video_urls: [],
    contact_name: "Demo Property Representative",
    contact_phone: "",
    status: "published",
    media_rights_confirmed: true,
    media_rights_note: "Demo imagery loaded from Unsplash. Replace with media you are authorised to publish.",
    is_demo: true,
    is_sponsored: false,
    visibility_starts_at: null,
    visibility_ends_at: null,
    created_at: "2026-01-01T00:00:00.000Z",
    updated_at: "2026-01-01T00:00:00.000Z"
  },
  {
    id: "demo-2",
    title: "Demo: Private Studio Near KNUST",
    description: "Demonstration inventory only. This record is not a verified property and must be replaced before public launch.",
    property_type: "Studio",
    location: "Kotei",
    city: "Kumasi",
    region: "Ashanti",
    address: "Kotei, Kumasi",
    latitude: null,
    longitude: null,
    monthly_rent: 2400,
    bedrooms: 1,
    bathrooms: 1,
    furnishing: "Partly furnished",
    room_type: "Private studio",
    occupants: 1,
    lease_term: "12 months",
    amenities: ["Water", "Internet-ready", "Parking"],
    image_urls: [
      "https://images.unsplash.com/photo-1522708323590-d24dbb6b0267?auto=format&fit=crop&w=1200&q=85",
      "https://images.unsplash.com/photo-1505693416388-ac5ce068fe85?auto=format&fit=crop&w=1200&q=85"
    ],
    video_urls: [],
    contact_name: "Demo Property Representative",
    contact_phone: "",
    status: "published",
    media_rights_confirmed: true,
    media_rights_note: "Demo imagery loaded from Unsplash. Replace with media you are authorised to publish.",
    is_demo: true,
    is_sponsored: false,
    visibility_starts_at: null,
    visibility_ends_at: null,
    created_at: "2026-01-02T00:00:00.000Z",
    updated_at: "2026-01-02T00:00:00.000Z"
  },
  {
    id: "demo-3",
    title: "Demo: Family House at Ahodwo",
    description: "Demonstration inventory only. This record is not a verified property and must be replaced before public launch.",
    property_type: "House",
    location: "Ahodwo",
    city: "Kumasi",
    region: "Ashanti",
    address: "Ahodwo, Kumasi",
    latitude: null,
    longitude: null,
    monthly_rent: 6500,
    bedrooms: 3,
    bathrooms: 3,
    furnishing: "Unfurnished",
    room_type: "3-bedroom house",
    occupants: 6,
    lease_term: "12 months",
    amenities: ["Parking", "Compound", "Water", "Security"],
    image_urls: [
      "https://images.unsplash.com/photo-1600585154340-be6161a56a0c?auto=format&fit=crop&w=1200&q=85",
      "https://images.unsplash.com/photo-1600607688969-a5bfcd646154?auto=format&fit=crop&w=1200&q=85"
    ],
    video_urls: [],
    contact_name: "Demo Property Representative",
    contact_phone: "",
    status: "published",
    media_rights_confirmed: true,
    media_rights_note: "Demo imagery loaded from Unsplash. Replace with media you are authorised to publish.",
    is_demo: true,
    is_sponsored: false,
    visibility_starts_at: null,
    visibility_ends_at: null,
    created_at: "2026-01-03T00:00:00.000Z",
    updated_at: "2026-01-03T00:00:00.000Z"
  }
];
